Feature/register Auth register new user
C-NodeJS/C-Side-BE pull request #4
Opened 2022-11-17 08:15 UTC by kentmonh

2022-11-17 08:21 UTC, dinhdung2207 commented on src/application/auth/auth.controller.ts
> +  async login(@Body() payload: RegisterPayload): Promise<any> {
change login function -> signUp function

2022-11-17 08:44 UTC, TranhGio requested changes
@kentmonh Please help me check this comments. Thank a lot!

2022-11-17 08:44 UTC, TranhGio commented on src/application/auth/dto/register.dto.ts
> +export class RegisterPayload {
Payload doesn't match with API document.
Please check again!

2022-11-17 08:44 UTC, TranhGio commented on src/application/auth/dto/register.dto.ts
> +export class RegisterPayload {
Using `RegisterRequestDTO` for this class name!

2022-11-17 08:44 UTC, TranhGio commented on src/application/auth/auth.service.ts
> +    if (payload.email) {
Please add `else` statement if you using this condition

2022-11-17 08:44 UTC, TranhGio commented on src/application/auth/auth.service.ts
> +    return user;
Return `access_token` for client using for redirect to HomePage

2022-11-18 06:55 UTC, kentmonh commented
Đã fix

2022-11-18 07:28 UTC, dinhdung2207 approved these changes

2022-11-18 07:42 UTC, hoang922 commented on src/application/auth/auth.service.ts
> +    return {
should return token and use presenter to response

2022-11-18 07:59 UTC, ThienLy3ky commented on src/infrastructure/data-access/typeorm/user.entity.ts
>      nullable: false,
```suggestion
    nullable: false,
```
nullable:false or true?

2022-11-18 08:01 UTC, ThienLy3ky commented on src/application/app.module.ts
> +import { UserModule } from './user/user.module';
```suggestion
import { UserModule } from './user/user.module';
```
redundant

2022-11-18 08:01 UTC, ThienLy3ky commented on src/application/app.module.ts
> +    UserModule, //TODO add more module to DI...
```suggestion
    UserModule, //TODO add more module to DI...
```
same

2022-11-18 08:06 UTC, TranhGio commented on src/application/auth/auth.service.ts
> +    if (payload.email) {
```suggestion
    if (!payload.email) {
       return {
          status_code: 9002,
          message: 'Bad request',
          error: 'Missing email!',
        };
    }
```

2022-11-22 02:11 UTC, TuanHai37 requested changes

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.service.ts
> +            messageCode: 'The email existed!',
mấy cái messageCode này e nghỉ a nên bỏ vào file common để lúc mà edit thì chỉ edit 1 chỗ thôi á a

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.module.ts
> +      secret: 'JWT_SECRET_KEY',
JWT_SECRET_KEY cái này a đang để secret là JWT_SECRET_KEY hay là a đang lấy env trong file config a nhỉ

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.service.ts
> +          error: 'Internal Server Error',
mấy cái này e nghĩ nên define ra lỗi rõ ràng . chứ kh có email mà báo lỗi 500 thế thì khó debug

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.service.ts
> +    } else {
cái này return thì khỏi cần else cũng được a
if có thì return cái đó còn nếu không mặc định return rồi. Khỏi cần else nữa cho rối

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.service.ts
> +        name: payload.name,
3 field này e thấy a đang required: false. thì nếu a không truyền thì vẫn pass. thì giờ payload.name -> lỗi

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.service.ts
> +      accessToken = this.jwtService.sign({
sao cái này a không lôi try catch ra hết đoạn code để a khai báo const  accessToken = this.jwtService.sign là được mà a nhỉ. try catch hết cả đoạn code cũng tốt mà. dễ nhìn hơn nữa

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/auth/auth.controller.ts
> +  @ApiResponse({ status: 1000, description: 'Success!' })
mấy cái này a nên define vào 1 file common. e thấy mn toàn trả về success với status thế này ở nhiều file nên lúc muốn sửa thì sửa ở rất nhiều chỗ

2022-11-23 03:42 UTC, kentmonh commented on src/application/auth/auth.service.ts
> +      accessToken = this.jwtService.sign({
Anh nghĩ try catch phần dễ tạo lỗi thôi thì debug khoẻ hơn

2022-11-23 03:42 UTC, kentmonh commented on src/application/auth/auth.controller.ts
> +  @ApiResponse({ status: 1000, description: 'Success!' })
Anh thấy dự án nhỏ thì viết như này khoẻ hơn, sửa thì tìm thôi

2022-11-23 03:43 UTC, kentmonh commented on src/application/auth/auth.service.ts
> +    } else {
Anh thì thấy viết if xong có else dễ đọc hơn

2022-11-24 02:56 UTC, TranhGio approved these changes
LGTM!

2022-11-24 02:56 UTC, merged