build api manage room
C-NodeJS/C-Side-BE pull request #8
Opened 2022-11-21 08:09 UTC by ThienLy3ky

2022-11-21 08:37 UTC, dinhdung2207 commented on src/application/room/dto/manage_room.dto.ts
> +export class Location {
Add new blank line to seperate 2 dto. 
Between variables and function should have blank line to seperate code. It will help us read code clearly.

Same error for remaning cases

2022-11-22 02:11 UTC, TuanHai37 requested changes

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/manage_room.service.ts
> +  async UpdateRoom(Room: CreateRoomRequestDTO): Promise<CreateRoomReponseDTO> {
UpdateRoom -> updateRoom

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/manage_room.service.ts
> +      room_id: room_id,
room_id: room_id ->  room_id,

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/manage_room.service.ts
> +    const room = await this.roomRepository.findOneBy({
findOneBy By gì a

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/manage_room.service.ts
> +    const [data, total] = await this.roomRepository.findAndCount({});
mấy cái getAll này nên phân trang a nhỉ. thằng fe trả về rồi a bỏ vào get từng đó thôi. a getAll thế này thì 1tr cái room thì performance lại kh ổn

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/dto/manage_room.dto.ts
> +  room_id: number;
cái room_id này là tự genarate ra mà a nhỉ

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/manage_room.controller.ts
> +  @Put('/')
cái này a truyền vào param /:room_id là ntn a nhỉ . Chứ dưới chỗ service a lôi cái room_id ở chỗ DTO ra là sai logic rồi

2022-11-22 02:11 UTC, TuanHai37 commented on src/application/room/dto/manage_room.dto.ts
> +export class Location {
e thấy cái class này a define ra nhưng mà a chưa dùng ở chỗ nào cả

2022-11-23 02:24 UTC, TranhGio requested changes
@ThienLy3ky Please take a look!

2022-11-23 02:24 UTC, TranhGio commented on src/application/room/dto/manage_room.dto.ts
> +  location: string;
Use class `Location` as below you define

2022-11-23 02:24 UTC, TranhGio commented on src/application/room/dto/manage_room.dto.ts
> +  long: number;
using `longtitude`

2022-11-23 02:24 UTC, TranhGio commented on src/application/room/dto/manage_room.dto.ts
> +  lat: number;
using `latitude`

2022-11-24 08:12 UTC, ThienLy3ky commented on src/application/room/manage_room.service.ts
> +    const room = await this.roomRepository.findOneBy({
a có để đk ở dưới e xem kĩ lại

2022-11-24 08:12 UTC, ThienLy3ky commented on src/application/room/manage_room.service.ts
> +    const [data, total] = await this.roomRepository.findAndCount({});
folow theo spec

2022-11-24 08:12 UTC, ThienLy3ky commented on src/application/room/dto/manage_room.dto.ts
> +  room_id: number;
genarate như thế nào?

2022-11-25 07:38 UTC, TranhGio commented on src/application/room/dto/manage_room.dto.ts
> +export class Location {
@ThienLy3ky Check and fix this comment!!!

2022-11-25 07:39 UTC, TranhGio commented on src/application/room/manage_room.controller.ts
> +  @Put('/:room_id')
Add break line between 2 function

2022-11-25 07:39 UTC, TranhGio commented on src/application/room/manage_room.controller.ts
> +  @Delete('/:room_id')
Add break line between 2 function

2022-11-25 07:40 UTC, TranhGio commented on src/application/room/manage_room.service.ts
> +  }
Add break line between 2 function

2022-11-25 07:40 UTC, TranhGio commented on src/application/room/manage_room.service.ts
> +  async getAllRoom({ pageSize, pageNumber }: GetQueryDTO, user) {
Add break line between 2 function

2022-11-25 07:40 UTC, TranhGio commented on src/application/room/manage_room.service.ts
> +  async getRoomDetail({ room_id }: IdRoomReponseDTO): Promise<RoomReponsDTO> {
Add break line between 2 function

2022-11-25 07:40 UTC, TranhGio commented on src/application/room/manage_room.service.ts
> +  async removeRoom({ room_id }: IdRoomReponseDTO): Promise<boolean> {
Add break line between 2 function

2022-11-25 08:02 UTC, TranhGio approved these changes
LGTM!

2022-11-30 08:58 UTC, merged